name: Reusable VPS Deploy

on:
  workflow_call:
    inputs:
      compose_file:
        required: true
        type: string
      remote_path:
        required: true
        default: docker-compose.yml
        type: string
    secrets:
      VPS_HOST:
        required: true
      VPS_USER:
        required: true
      VPS_PRIVATE_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ inputs.remote_path }}
            git pull origin main
            docker compose -f ${{ inputs.compose_file }} down
            docker compose -f ${{ inputs.compose_file }} build
            docker compose -f ${{ inputs.compose_file }} up -d